// <auto-generated />
namespace Lab1Week11.Migrations.ClubContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Dateschanged : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Dateschanged));
        
        string IMigrationMetadata.Id
        {
            get { return "201712061015082_Dates changed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
